name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Any Name Bash Test Step
      shell: bash
      run: |
      echo "${{ secrets.DEPLOY_KEY }}"
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: /
        remote_path: BatoStarter/
        remote_host: 31.131.18.34
        remote_port: 21098
        remote_user: batowebd
        remote_key: ${{ secrets.DEPLOY_KEY }}
