name: DEPLOY
on: [push]
jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to my ❤️
      uses: up9cloud/action-rsync@v1.1
      env:
        HOST: ${{ secrets.DEPLOY_HOST }}
        KEY: ${{ secrets.DEPLOY_KEY }}
        TARGET: BatoStarter/

        VERBOSE: true
        USER: ${{ secrets.DEPLOY_USER }}
        # PORT: 2222 # no need to set this, because of $SSH_ARGS
        ARGS: -az --exclude=/.git/
        PRE_SCRIPT: |
          echo start at:
          date -u
        POST_SCRIPT: "echo done at: && date -u"