name: Build and deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  buildComposer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install and build with Composer
      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-all

      - name: Install Composer dependencies root
        run:  composer install --ignore-platform-reqs

      - name: Install composer in theme
        working-directory: ./web/app/themes/sage
        run: |
          composer install --ignore-platform-reqs
  
  buildNodeModules:
    needs: [buildComposer]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2 
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Install node modules 
          working-directory: ./web/app/themes/sage
          run: yarn install

  deploy:
    needs: [buildComposer,buildNodeModules]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: /
        remote_host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
        remote_path: BatoStarter
