name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    env:
      key1: ${{secrets.DEPLOY_KEY}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo $key1
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: /
        remote_path: BatoStarter/
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
